apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-db-pvc
  namespace: task-management
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: standard